# Generated by Django 6.0.7 on 2026-07-28 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_guest_name_alter_conversation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="active_seconds",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Approximate active time spent using this conversation, measured in seconds.",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent recorded active-use heartbeat.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="session_ended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time the participant ended the CoachBot session.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="session_started_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Time the CoachBot session began.",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="visitor_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anonymous browser identifier used to recognize repeat guest users.",
                max_length=64,
            ),
        ),
    ]
