# Generated by Django 6.0.7 on 2026-07-28 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_usagelog_guest_name_alter_usagelog_user"),
        ("conversations", "0002_conversation_guest_name_alter_conversation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachbotFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usefulness",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Not useful, 5 = Extremely useful",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        help_text="1 = Not confident, 5 = Extremely confident",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "improvement_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Open-ended feedback about how the CoachBot can improve.",
                        max_length=5000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "CoachBot feedback",
                "verbose_name_plural": "CoachBot feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
