# Generated by Django 6.0.7 on 2026-07-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_coachbotfeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usagelog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="coachbotfeedback",
            name="is_repeat_user",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the participant had a prior CoachBot conversation.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachbotfeedback",
            name="session_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Approximate active time spent using the CoachBot, measured in seconds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coachbotfeedback",
            name="visit_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The participant's conversation number across the application.",
                null=True,
            ),
        ),
    ]
